### ISSUE TITLE
Setup CI / CD

### ISSUE THREAD

**Issue by jamesrweb** [accessibility-tools/CI#18]
### Subject of the issue

CI / CD are not currently setup. The plan would be to remediate this via Github Actions.

### Expected behaviour

When a milestone is reached and the `develop` branch is merged into `master` we should run the CD process (build + deploy) automatically. Before a branch is merged into any other, we should first run the CI process (code style + tests). All of this should be acomplished via Github Actions and split into seperate configurations due to their nature.

The current plan is to use the following tools for the CI step:

- [Jest](https://jestjs.io/) for testing
- [Standard](https://standardjs.com/) for code formatting

The current plan is to use the following tools for the CD step:

- [TypeScript](https://www.typescriptlang.org/) for the build step
- [NPM CLI](https://docs.npmjs.com/cli-documentation/cli) for the release step

For both CI / CD, we will utilise [Github Actions](https://github.com/features/actions) as our runner.

### Actual behaviour

Currently we are manually checking code style, functionality, builds and releases. All of these areas should be automated so that developers can do what they do best... develop!

### Final notes

Comments and feedback welcome, new ideas or help appreciated also.

**Comment by jamesrweb** [comment]
@egor-sorokin happy for your thoughts on this topic

**Comment by egor-sorokin** [comment]
Hm, I haven't had any experience with CI / CD in terms of configuration and setting things up. In terms of the stack (Jest, Standard, TS and npm cli) it looks really cool!

**Comment by jamesrweb** [comment]
@egor-sorokin alright, I will work on that later this week and when I finish up I will PR for you to review then. If you have any comments or ideas in the meantime, add them here 😄.
